### ISSUE TITLE
Issue in Module- 1, DEVWF-T007

### ISSUE THREAD

**Issue by Shivashant25** [XpiritBV/CodeToCloud-Workshop#72]
In step- 11, the provided YAML code's indentation is wrong, I tried fixing it using the YAML validator. In the validator, the code's indentation is correct. But when I use the same code in Github. The indentation is wrong. I tried to commit the file. but it got failed.

![image](https://user-images.githubusercontent.com/81952290/126650638-7b0f9892-0f7e-4a6c-a659-c92f2358308e.png)

![image](https://user-images.githubusercontent.com/81952290/126649884-18854e24-3d4a-44fd-a0f9-edd9c18f1e8f.png)

**Comment by cdijkstra** [comment]
Thanks for your feedback. This issue has been resolved [here](https://github.com/XpiritBV/CodeToCloud-Workshop/commit/0d16b7352886cf2e6ceafe6ecf0b986536e829c3)
