### ISSUE TITLE
Issue in Module -1, DEVWF-T004

### ISSUE THREAD

**Issue by Shivashant25** [XpiritBV/CodeToCloud-Workshop#78]
In step- 1, The command provided to create the pull request (that contains the multi-staged Docker file for the WEB, API, and INIT applications) is not working as expected. Getting few errors. I notice that the path has been changed. 

Screenshot from the lab guide:
![image](https://user-images.githubusercontent.com/81952290/127659297-ad4341a1-1b47-44c5-9df9-5cb8b32a87be.png)
 
Actual output:
![image](https://user-images.githubusercontent.com/81952290/127659213-8172e2aa-c9ef-4f30-9beb-02dd18c1211d.png)

**Comment by cdijkstra** [comment]
Thanks for the update, I'll change it to the right repo!

**Comment by cdijkstra** [comment]
Did you execute this command from Github Codespaces?

**Comment by Shivashant25** [comment]
Yes

**Comment by cdijkstra** [comment]
Are you still having this issue? The upstream is `https://github.comXpiritBV/CodeToCloud-Source` in my `Workshop-Step Start/Stop` commands

**Comment by Shivashant25** [comment]
The issue has been solved. It's working now. Thank you

**Comment by cdijkstra** [comment]
Great, thanks for the verification!
